name: ZMK Build and Flash

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        board: ["nice_nano_v2"]
        shield: ["NesPad"]

    steps:
      - name: Checkout ZMK repository
        uses: actions/checkout@v2

      - name: Set up ZMK environment
        run: |
          echo "ZMK_CONFIG_DIR=/Users/mnrdsgn/keebra/zmk-config-NesPad" >> $GITHUB_ENV
          echo "ZMK_EXTRA_MODULES=/Users/mnrdsgn/keebra/zmk-config-NesPad" >> $GITHUB_ENV

      - name: Run ZMK build
        run: |
          rm -rf build/nespad_studio
          west build -d build/nespad_studio -b nice_nano_v2 \
            -S studio-rpc-usb-uart -S zmk-usb-logging -- \
            -DSHIELD=${{ matrix.shield }} \
            -DZMK_CONFIG="${{ env.ZMK_CONFIG_DIR }}/config" \
            -DZMK_EXTRA_MODULES="${{ env.ZMK_EXTRA_MODULES }}" \
            -DCONFIG_ZMK_STUDIO=y

      - name: Upload build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: zmk-build
          path: build/nespad_studio
