name: Build ZMK Firmware

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest  # or macos-latest, depending on the platform
    strategy:
      matrix:
        board: ["nice_nano_v2"]
        shield: ["NesPad"]
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Set up Zephyr environment
        run: |
          # Commands to set up Zephyr and dependencies

      - name: Build ZMK firmware
        run: |
          west build -d build/nespad_studio -b ${{ matrix.board }} \
            -S studio-rpc-usb-uart -S zmk-usb-logging -- \
            -DSHIELD=${{ matrix.shield }} \
            -DZMK_CONFIG="/Users/mnrdsgn/keebra/zmk-config-NesPad/config" \
            -DZMK_EXTRA_MODULES="/Users/mnrdsgn/keebra/zmk-config-NesPad" \
            -DCONFIG_ZMK_STUDIO=y
