 file_format: "1"
id: nespad
name: NesPad
type: shield
url: https://github.com/eboy79/zmk-config-NesPad
requires: [nice_nano_v2]
exposes: [ws2812]
features:
  - underglow
  - studio
outputs:
  - usb
  - ble
